### ISSUE TITLE
能否用shell重构一下

### ISSUE THREAD

**Issue by lwy7654321** [TeddyNight/sms_forwarder_mmcli#1]
能否用shell重构一下，使脚本部署无需依赖python(或许内存开销会更小)
或者大概描述一下原理，我自己看能不能用shell实现出来
感谢

**Comment by TeddyNight** [comment]
这个是利用dbus(类似推送的功能?)做的，我觉得开销差不多了，我自己512+4的配置，运行也就不过10M内存。shell脚本可能不考虑了(扩展维护之类我觉得不太方便)，shell的话直接参照openstick wiki里那个sms脚本就行，那个是直接用命令行拉取。反正总而言之吧，(也不一定准确)，cron定期开脚本，又是启动bash，又是启动mmcli的，进程开销很大;我这个平常应该是空闲的，只是等到信息到了，回调函数才开始工作。
